<?php
/**
 * TurnTo_SocialCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2017 TurnTo Networks, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * This file is analogous to the root.phtml file in the Magento_Theme module. It is the parent-most template and is
 * used by the \TurnTo\SocialCommerce\Framework\View\Result\PageBlank class to render the layout content.
 */
?>
<?php /* @escapeNotVerified */ echo $layoutContent ?>
