<?php
/**
 * Copyright © Emplifi, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use TurnTo\SocialCommerce\Block\TurnToConfig;
use TurnTo\SocialCommerce\Model\Config;

/**
 * @var TurnToConfig $block
 */
$siteKey = $block->getSiteKey();
?>
<script type="text/javascript">
    (function (window) {
        window.turnToConfig = <?= $block->getJavaScriptConfig() ?>;
        window.TurnToCmd = window.TurnToCmd || function () {
            (TurnToCmd.q = TurnToCmd.q || []).push(arguments);
        };
    })(window);
</script>

<script type="text/x-magento-init">
    {
        "*": {
            "turnToConfig": {}
        }
    }

</script>


<?php if ($siteKey): ?>
    <script src="<?= $block->getConfigValue(Config::PRODUCT_WIDGET_URL) ?><?= Config::SOCIALCOMMERCE_VERSION ?>/widgets/<?= $siteKey ?>/js/turnto.js"
            type="text/javascript" async></script>
<?php endif; ?>

<?= $block->getChildHtml() ?>
