<?php /** @var \TurnTo\SocialCommerce\Block\TurnToConfigInterface $block */ ?>
<?php
/** @var TurnTo\SocialCommerce\Helper\Config $configHelper */
$configHelper = $this->helper(\TurnTo\SocialCommerce\Helper\Config::class);
$siteKey = $configHelper->getSiteKey();
$version = $configHelper->getTurnToVersion();
?>
<script type="text/javascript">
    (function (window) {
        window.turnToConfig = <?= $block->getJavaScriptConfig() ?>;
        window.TurnToCmd = window.TurnToCmd || function () {
            (TurnToCmd.q = TurnToCmd.q || []).push(arguments);
        };
    })(window);
</script>



<?php if ($siteKey): ?>
    <script src="<?= $configHelper->getWidgetUrl() ?><?= $version ? $version : 'v5' ?>/widgets/<?= $siteKey ?>/js/turnto.js"
            type="text/javascript" async></script>
<?php endif; ?>

<?= $block->getChildHtml() ?>
