<?php
/**
 * Copyright © Emplifi, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Backend\Block\Template;
use TurnTo\SocialCommerce\Model\Config;
use TurnTo\SocialCommerce\ViewModel\Widget as ViewModel;

/**
 * @var Template $block
 * @var ViewModel $viewModel
 */
$viewModel = $block->getViewModel();

$staticUrl = $viewModel->getConfigValue(Config::PRODUCT_STATIC_API_URL);
$version = Config::SOCIALCOMMERCE_VERSION;
?>

<script type="text/javascript" src="<?= sprintf('%s/tra%s/mobile-landing.js', $staticUrl, $version) ?>"></script>
