version: 2.1

executors:
  default:
    docker:
      - image: docker.io/bitnami/mariadb:10.3-debian-10
        environment:
          ALLOW_EMPTY_PASSWORD: yes
          MARIADB_USER: bn_magento
          MARIADB_PASSWORD: magento_db_password
          MARIADB_DATABASE: bitnami_magento
      - image: docker.io/bitnami/magento:2.4.1
        environment:
          MAGENTO_HOST: localhost
          MAGENTO_DATABASE_HOST: mariadb
          MAGENTO_DATABASE_PORT_NUMBER: 3306
          MAGENTO_DATABASE_USER: bn_magento
          MAGENTO_DATABASE_PASSWORD: magento_db_password
          MAGENTO_DATABASE_NAME: bitnami_magento
          ELASTICSEARCH_HOST: elasticsearch
          ELASTICSEARCH_PORT_NUMBER: 9200
          ALLOW_EMPTY_PASSWORD: yes
      - image: docker.io/bitnami/elasticsearch:6-debian-10
    environment:
      TEST_RESULTS: /tmp/test-results
      PATH_TO_MAGENTO: magento/dev/tests/integration

workflows:
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build

jobs:
  build:
    executor: default
    steps:
      - checkout
      - build-magento
      - persist-workspace
  test:
    executor: default
    steps:
      - attach-workspace
      - run-tests

commands:
  build-magento:
    steps:
      - run:
          name: run magento commands
          command: php bin/magento setup:upgrade

  persist-workspace:
    steps:
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  
  attach-workspace:
    steps:
      - attach_workspace:
          at: ~/repo
  
  run-tests:
    steps:
      - run:
          name: run php unit tests
          command: ./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/TurnTo/SocialCommerce/Test/Unit