version: 2.1

executors:
  default:
    docker:
      - image: cimg/php:7.2.32

workflows:
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build

jobs:
  build:
    executor: default
    steps:
      - install-magento
      - checkout
      - move-repo
      - build-magento
      - persist-workspace
  test:
    executor: default
    steps:
      - attach-workspace
      - run-tests

commands:
  install-magento:
    steps:
      - run:
          name: download and install Magento 2
          command: composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition ./

  move-repo:
    steps:
      - run:
          name: make app/code/TurnTo/SocialCommerce dir and copy repo there
          command: mkdir -p app/code/TurnTo/SocialCommerce && ls ~/*

  build-magento:
    steps:
      - run:
          name: run magento commands
          command: php bin/magento setup:upgrade

  persist-workspace:
    steps:
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  
  attach-workspace:
    steps:
      - attach_workspace:
          at: ~/repo
  
  run-tests:
    steps:
      - run:
          name: run php unit tests
          command: ./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/TurnTo/SocialCommerce/Test/Unit