version: 2

jobs:
  build:
    docker:
      - image: docker.io/bitnami/mariadb:10.3-debian-10
        environment:
          ALLOW_EMPTY_PASSWORD: yes
          MARIADB_USER: bn_magento
          MARIADB_PASSWORD: magento_db_password
          MARIADB_DATABASE: bitnami_magento
      - image: docker.io/bitnami/magento:2.4.1
        environment:
          MAGENTO_HOST: localhost
          MAGENTO_DATABASE_HOST: mariadb
          MAGENTO_DATABASE_PORT_NUMBER: 3306
          MAGENTO_DATABASE_USER: bn_magento
          MAGENTO_DATABASE_PASSWORD: magento_db_password
          MAGENTO_DATABASE_NAME: bitnami_magento
          ELASTICSEARCH_HOST: elasticsearch
          ELASTICSEARCH_PORT_NUMBER: 9200
          ALLOW_EMPTY_PASSWORD: yes
      - image: docker.io/bitnami/elasticsearch:6-debian-10
    environment:
      TEST_RESULTS: /tmp/test-results
      PATH_TO_MAGENTO: magento/dev/tests/integration

