version: 2.1

executors:
  default:
    docker:
      - image: cimg/php:7.2.32

workflows:
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build

jobs:
  build:
    executor: default
    steps:
      - setup-environment
      - install-magento
      - checkout-repo
      - build-magento
      - persist-workspace
  test:
    executor: default
    steps:
      - attach-workspace
      - run-tests

commands:
  setup-environment:
    steps:
      - run:
          name: install magento dependencies
          command: sudo apt-get update && sudo apt-get install php7.2-bcmath && sudo apt-get install php7.2-intl && sudo apt-get install php7.2-soap

  install-magento:
    steps:
      - run:
          name: download and install Magento 2
          command: git clone -b 2.3 https://github.com/magento/magento2 ./ && composer install && mkdir -p app/code/TurnTo/SocialCommerce

  checkout-repo:
    steps:
      - run:
          name: checkout extension repo to proper directory
          command: git clone app/code/TurnTo/SocialCommerce

  build-magento:
    steps:
      - run:
          name: run magento commands
          command: php bin/magento setup:upgrade && php bin/magento setup:di:compile

  persist-workspace:
    steps:
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  
  attach-workspace:
    steps:
      - attach_workspace:
          at: ~/repo
  
  run-tests:
    steps:
      - run:
          name: run php unit tests
          command: ./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist app/code/TurnTo/SocialCommerce/Test/Unit