<?php
/**
 * Copyright © Emplifi, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Backend\Block\Template;
use TurnTo\SocialCommerce\Model\Config;
use TurnTo\SocialCommerce\ViewModel\Widget as ViewModel;

/**
 * @var Template $block
 * @var ViewModel $viewModel
 */
$viewModel = $block->getViewModel();
?>

<?php if($viewModel->getConfigValue(Config::CHECKOUT_ENABLE_TOP_COMMENTS)): ?>
<div class="tt-top-comment" data-ttsku="<?= $viewModel->getProductSku() ?>"></div>
<?php endif; ?>
