<?php
/**
 * TurnTo_SocialCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2016 TurnTo Networks, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

$configHelper = $this->helper('TurnTo\SocialCommerce\Helper\Config');

$siteKey = $configHelper->getSiteKey();
$staticUrl = preg_replace("(^https?://)", "//", $configHelper->getStaticUrl());
$version = $configHelper->getTurnToVersion();
$locale = $this->getLocale();

$reviewsEnabled = $configHelper->getReviewsEnabled();
$qaEnabled = $configHelper->getQaEnabled();
$commentsEnabled = $configHelper->getCheckoutCommentsEnabledProductDetail();
$reviewsTeaserEnabled = $configHelper->getReviewsTeaserEnabled();
$qaTeaserEnabled = $configHelper->getQaTeaserEnabled();
$galleryEnabled = $configHelper->getGalleryEnabled();

$productSku = $this->getProduct()->getSku();

if ($reviewsEnabled || $qaEnabled || $commentsEnabled):
?>

<link rel="stylesheet" href="<?= sprintf('%s/tra%s/tra.css', $staticUrl, $version) ?>" />

<?php if($galleryEnabled): ?>
<link rel="stylesheet" href="<?= sprintf('%s/tra%s/turnto-gallery-%s.css', $staticUrl, $version, $locale ) ?>" />
<?php endif; ?>

<script type="text/javascript">
    require([
        '<?= sprintf('%s/sitedata/%s/v%s/%s/d/itemjs', $staticUrl, $siteKey, $version, $productSku) ?>',
        '<?= sprintf('%s/traServer%s/trajs/%s/tra.js', $staticUrl, $version, $siteKey) ?>',
        '<?= $commentsEnabled ? sprintf('%s/traServer%s/chatterjs/%s/turnto-chatter.js', $staticUrl, $version, $siteKey) : '' ?>',
        '<?= $galleryEnabled ? sprintf('%s/traServer%s/galleryjs/%s/turnto-gallery.js/%s', $staticUrl, $version, $siteKey, $locale) : '' ?>'
    ]);

    <?php if($qaTeaserEnabled && $qaEnabled): ?>
    function qaTeaser () {
        if(typeof(TurnToItemData) == 'undefined' || typeof(TurnToItemData.counts) == 'undefined') {
            return '';
        } else {
            var answerCount = TurnToItemData.counts.a;
            var questionCount = TurnToItemData.counts.q;
            var teaserContainer = TurnTojQuery(".TurnToItemTeaser");
            var teaserHtml = '';
            <?php
                if ($reviewsEnabled && $reviewsTeaserEnabled):
            ?>
            var teaserHtml = '&nbsp;|&nbsp;';
            <?php
                endif;
            ?>

            if(questionCount == 0) {
                teaserHtml = teaserHtml + '<a id="askQuestion" href="javascript:void(0)"><?= __('Ask a Question') ?></a>';
            } else {
                teaserHtml = teaserHtml + '<a id="readQuestions" href="javascript:void(0)">' + questionCount + ' Question' + (questionCount == 1 ? '' : 's') + ', ' + answerCount + ' Answer' + (answerCount == 1 ? '' : 's') + '</a>';
            }

            var reviewCount = TurnToItemData.counts.r;

            // Fill container with Q&A content
            teaserContainer.html(teaserHtml);

            // Add the appropriate listeners to the links
            scrollToTab(teaserContainer, '#askQuestion', '#turnto_qa','#tab-label-turnto_qa-title');

            scrollToTab(teaserContainer, '#readQuestions', '#turnto_qa','#tab-label-turnto_qa-title');
        }
    }
    <?php endif; ?>

    <?php if($reviewsTeaserEnabled && $reviewsEnabled): ?>
    function reviewsTeaser() {
        if(typeof(TurnToItemData) == 'undefined' || typeof(TurnToItemData.counts) == 'undefined') {
            return '';
        } else {
            var reviewCount = TurnToItemData.counts.r;
            var teaserContainer = TurnTojQuery(".TurnToReviewsTeaser");
            var teaserHtml = '';

            // round the average rating to the nearest tenth
            var rating = Math.round((TurnToItemData.counts.ar + 0.25) * 100.0) / 100.0;
            rating = rating.toString();
            var decimal = parseInt(rating.substring(2, 3));
            rating = rating.substring(0, 1) + "-" + (decimal >= 5 ? '5' : '0');

            if(reviewCount == 0) {
                teaserHtml = '<div class="TT2left TTratingBox TTrating-0-0"></div> <a id="writeReview" href="javascript:void(0)"><?= __('Write a Review') ?></a>';
            } else {
                teaserHtml = '<div class="TTratingBox TTrating-' + rating + '"></div><a id="readReviews" href="javascript:void(0)">' + reviewCount + ' Review' + (reviewCount == 1 ? '' : 's') + '</a>';
            }

            teaserContainer.html(teaserHtml);

            scrollToTab(teaserContainer, '#readReviews', '#turnto_reviews', '#tab-label-turnto_reviews-title');

            // Listener on 'write review' link
            teaserContainer.find('#writeReview').click(function(e) {
                TurnTo.writeReview();
            });
        }
    }
    <?php endif; ?>

    function scrollToTab(teaserContainer, clickElement, container, tab) {
        teaserContainer.find(clickElement).click(function(e) {
            e.preventDefault();
            if(!jQuery(tab).parent().hasClass('active')) {
                jQuery(tab).click();
            }
            jQuery("html, body").animate({ scrollTop: jQuery(container).offset().top - 20 }, 1000);
        });
    }


    var turnToConfig = <?= $block->getConfigJson() ?>;

    var TurnToItemSku = "<?= $productSku ?>";

    <?php if($commentsEnabled): ?>
    var TurnToChatterSku = TurnToItemSku;
    <?php endif; ?>

    <?php if($galleryEnabled): ?>
    var TurnToGallerySkus = TurnToItemSku;
    <?php endif; ?>

</script>
<?php endif; ?>

