<?php
/**
 * Copyright © Emplifi, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Backend\Block\Template;
use TurnTo\SocialCommerce\ViewModel\ConfigJs as ViewModel;

/**
 * @var Template $block
 * @var ViewModel $viewModel
 */
$viewModel = $block->getViewModel();
?>

<?php if ($viewModel->getIsEnabled()): ?>
<script type="text/javascript">
    (function (window) {
        window.scrollToTab = function scrollToTab(teaserContainer, clickElement, container, tab) {
            teaserContainer.find(clickElement).click(function (event) {
                event.preventDefault();

                if (!jQuery(tab).parent().hasClass('active')) {
                    jQuery(tab).click();
                }

                jQuery('html, body').animate({scrollTop: jQuery(container).offset().top - 20}, 500);
            });
        };

        <?php if ($productSku = $viewModel->getProductSku()): ?>
        window.TurnToCmd('set', {'sku': '<?= $block->escapeJsQuote($productSku) ?>'});
        <?php endif; ?>
    })(window);
</script>
<?php endif; ?>

