<?php
/**
 * TurnTo_SocialCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2018 TurnTo Networks, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var \Magento\Catalog\Block\Product\View $block */
$configHelper = $this->helper('TurnTo\SocialCommerce\Helper\Config');
$productHelper = $this->helper('TurnTo\SocialCommerce\Helper\Product');

?>

<div id="tt-reviews-summary"></div>
<div id="tt-reviews-list"></div>




<script type="text/x-magento-init">
        {
            "#tt-reviews-summary": {
                "Magento_Ui/js/core/app": {
                   "components": {
                        "reviews": {
                            "component": "TurnTo_SocialCommerce/js/reviews-tab",
                            "config": {
                                "siteKey": "<?= $configHelper->getSiteKey() ?>",
                                "reviewSku": "<?= $productHelper->turnToSafeEncoding($productHelper->getProductSku()) ?>",
                                "reviewsEnabled": "<?= $configHelper->getReviewsEnabled() ? 'true' : 'false' ?>",
                                "reviewsUrl": "<?= $configHelper->getTeaserUrl()?>"

                            }
                        }
                    }
                }
            }
        }
</script>
