<?php
/**
 * Copyright © Emplifi, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Review\Block\Product\Review;
use TurnTo\SocialCommerce\Model\Config;
use TurnTo\SocialCommerce\ViewModel\Widget as ViewModel;

/**
 * @var Review $block
 * @var ViewModel $viewModel
 */
$viewModel = $block->getViewModel();
?>

<div id="tt-reviews-summary"></div>
<div id="tt-reviews-list"></div>
<script type="text/x-magento-init">
        {
            "#tt-reviews-summary": {
                "Magento_Ui/js/core/app": {
                   "components": {
                        "reviews": {
                            "component": "TurnTo_SocialCommerce/js/reviews-tab",
                            "config": {
                                "siteKey": "<?= $viewModel->getSiteKey() ?>",
                                "reviewSku": "<?= $viewModel->getProductSku() ?>",
                                "reviewsEnabled": "<?= $viewModel->getConfigBool(Config::REVIEWS_ENABLE) ? 'true' : 'false' ?>",
                                "reviewsUrl": "<?= $viewModel->getConfigValue(Config::PRODUCT_REVIEW_URL) ?>"
                            }
                        }
                    }
                }
            }
        }
</script>
