<?php
/**
 * TurnTo_SocialCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2017 TurnTo Networks, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

$configHelper = $this->helper('TurnTo\SocialCommerce\Helper\Config');

$reviewsEnabled = $configHelper->getReviewsEnabled();
$qaEnabled = $configHelper->getQaEnabled();
$reviewsTeaserEnabled = $configHelper->getReviewsTeaserEnabled();
$qaTeaserEnabled = $configHelper->getQaTeaserEnabled();

if ($reviewsEnabled && $reviewsTeaserEnabled){
    echo '<span class="TurnToReviewsTeaser"></span>';
}

if ($qaEnabled && $qaTeaserEnabled) {
    echo '<span class="TurnToItemTeaser"></span>';
}
