<?php
/**
 * TurnTo_SocialCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2018 TurnTo Networks, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var \Magento\Catalog\Block\Product\View $block */
$configHelper = $this->helper('TurnTo\SocialCommerce\Helper\Config');

?>
<div id="tt-teaser" class="TTteaser" data-bind="scope:'teaser'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#tt-teaser": {
                "Magento_Ui/js/core/app": {
                   "components": {
                        "teaser": {
                            "component": "TurnTo_SocialCommerce/js/teaser",
                            "config": {
                                "siteKey": "<?= $configHelper->getSiteKey() ?>",
                                "teaserSku": "<?= $block->getProduct()->getSku() ?>",
                                "reviewsEnabled": "<?= $configHelper->getReviewsEnabled() ? 'true' : 'false' ?>",
                                "reviewsTeaserEnabled": "<?= $configHelper->getReviewsTeaserEnabled() ? 'true' : 'false' ?>",
                                "qaEnabled": "<?= $configHelper->getQaEnabled() ? 'true' : 'false' ?>",
                                "qaTeaserEnabled": "<?= $configHelper->getQaTeaserEnabled() ? 'true' : 'false' ?>",
                                "commentsEnabled": "<?= $configHelper->getCheckoutCommentsEnabled() ? 'true' : 'false' ?>",
                                "commentsTeaserEnabled": "<?= $configHelper->getCommentsTeaserEnabled() ? 'true' : 'false' ?>",
                                "teaserUrl": "<?= $configHelper->getTeaserUrl()?>"
                            }
                        }
                    }
                }
            }
        }
    </script>
</div>
