<?php
/**
 * Copyright © Emplifi, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Catalog\Block\Product\View;
use TurnTo\SocialCommerce\Model\Config;
use TurnTo\SocialCommerce\Model\Config\Source\TeaserType;
use TurnTo\SocialCommerce\ViewModel\Widget as ViewModel;

/**
 * @var View $block
 * @var ViewModel $viewModel
 */
$viewModel = $block->getViewModel();
?>
<?php if ($viewModel->getConfigValue(Config::TEASER_LOCAL_TEASER_CODE) == TeaserType::TEASER_LOCAL): ?>
    <div id="tt-teaser" class="TTteaser" data-bind="scope:'teaser'">
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#tt-teaser": {
                    "Magento_Ui/js/core/app": {
                       "components": {
                            "teaser": {
                                "component": "TurnTo_SocialCommerce/js/teaser",
                                "config": {
                                    "siteKey":
                                        "<?= $block->escapeJs($viewModel->getSiteKey()) ?>",
                                    "teaserSku":
                                        "<?= $block->escapeJs($viewModel->getProductSku()) ?>",
                                    "reviewsEnabled":
                                        "<?= $block->escapeJs($viewModel->getConfigBoolString(Config::REVIEWS_ENABLE)) ?>",
                                    "reviewsTeaserEnabled":
                                        "<?= $block->escapeJs($viewModel->getConfigBoolString(Config::TEASER_REVIEWS_TEASER_ENABLE)) ?>",
                                    "qaEnabled":
                                        "<?= $block->escapeJs($viewModel->getConfigBoolString(Config::QA_ENABLE)) ?>",
                                    "qaTeaserEnabled":
                                        "<?= $block->escapeJs($viewModel->getConfigBoolString(Config::TEASER_ENABLE_QA_TEASER)) ?>",
                                    "commentsTeaserEnabled":
                                        "<?= $block->escapeJs($viewModel->getConfigBoolString(Config::TEASER_ENABLE_COMMENTS_TEASER)) ?>",
                                    "teaserUrl":
                                        "<?= $block->escapeJs($viewModel->getConfigValue(Config::PRODUCT_REVIEW_URL) ?: '') ?>"
                                }
                            }
                        }
                    }
                }
            }
        </script>
    </div>
<?php else: ?>
    <div id="tt-teaser-widget"></div>
<?php endif ?>
