<?php
/**
 * TurnTo_SocialCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2016 TurnTo Networks, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var TurnTo\SocialCommerce\Helper\Config $configHelper */
$configHelper = $this->helper('TurnTo\SocialCommerce\Helper\Config');

$siteKey = $configHelper->getSiteKey();
$staticUrl = preg_replace("(^https?://)", "//", $configHelper->getStaticUrl());
$version = $configHelper->getTurnToVersion();
$setupType = $configHelper->getSetupType();
?>

<div class="TTAccountForm">
    <?= $this->getChildHtml('turnto_frontend_sso_logo') ?>
    <?= $block->getChildHtml('form-fields') ?>
    <?php echo $block->getChildHtml('form-extras'); ?>
</div>

<script type="text/javascript">
    var turnToConfig = {
        siteKey: "<?= $siteKey ?>",
        setupType: "<?= $setupType ?>"
    };

    require([
        'jquery',
        'mage/url',
        'mage/validation',
        '<?= sprintf('%s/traServer%s/trajs/%s/tra.js', $staticUrl, $version, $siteKey) ?>'
    ], function ($, urlBuilder) {
        'use strict';

        var form = $('form');
        urlBuilder.setBaseUrl("<?= $block->getBaseUrl() ?>");

        form.on('submit', function (event) {
            event.preventDefault();
            if (form.validation() && form.validation('isValid')) {
                $.ajax({
                    url: urlBuilder.build('<?= $block->getPostUrl() ?>'),
                    method: "POST",
                    data: $('form').serialize(),
                    dataType: 'json',
                    showLoader: true
                }).done(function (response) {
                    if (response.success) {
                        TurnTo.localAuthenticationComplete();
                    } else {
                        // Reload the page to display any error messages
                        location.reload(true);
                    }
                });
            }
        });
    });
</script>
