<?php
/**
 * TurnTo_SocialCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2016 TurnTo Networks, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/**
 * Links on the page such as the Forgot Your Password Link and links displayed in error messages should not be opened
 * from within the context of the iFrame. The user should be navigated to the page from the main page for a better
 * user experience.
 */
?>
<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        $('body').on('click', '.action.remind, .messages a', function (event) {
            event.preventDefault();
            top.window.location.href = $(this).attr('href');
        });
    });
</script>
