<?php
/**
 * TurnTo_SocialCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2016 TurnTo Networks, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

$configHelper = $this->helper('TurnTo\SocialCommerce\Helper\Config');

$siteKey = $configHelper->getSiteKey();
$url = $configHelper->getUrl();
$staticUrl = preg_replace("(^https?://)", "//", $configHelper->getStaticUrl());
$version = $configHelper->getTurnToVersion();
$checkoutCommentsSuccessEnabled = var_export((bool)$configHelper->getCheckoutCommentsEnabledCheckoutSuccess(), true);

?>
<script type="text/javascript">
    var turnToConfig = {
        siteKey: "<?= $siteKey ?>",
        orderConfFlowPauseSeconds:0,
        commentCaptureShowUsername: true,
        postPurchaseFlow:true,
        embedCommentCapture: <?= $checkoutCommentsSuccessEnabled ?>
    };
</script>

<script src='<?= $staticUrl ?>/tra<?= $version ?>/turntoFeed.js' type='text/javascript'></script>

<script src='<?= $staticUrl ?>/traServer<?= $version ?>/trajs/<?= $siteKey ?>/tra.js' type='text/javascript'></script>

<script type="text/javascript">
    TurnToFeed.addFeedPurchaseOrder(<?= $block->getFeedPurchaseOrderData() ?>);

    <?php foreach($block->getOrderItemData() as $item): ?>
            TurnToFeed.addFeedLineItem(<?= $item ?>);
    <?php endforeach; ?>

    TurnToFeed.sendFeed();
</script>

<?php if ($checkoutCommentsSuccessEnabled): ?>
    <div id="TTcommentCapture"></div>
<?php endif; ?>