<?php

$configHelper = $this->helper('TurnTo\SocialCommerce\Helper\Config');

$siteKey = $configHelper->getSiteKey();
$url = $configHelper->getUrl();
$staticUrl = preg_replace("(^https?://)", "//", $configHelper->getStaticUrl());
$version = $configHelper->getTurnToVersion();
$checkoutCommentsSuccessEnabled = (bool)$configHelper->getCheckoutCommentsEnabledCheckoutSuccess();

?>
<script type="text/javascript">
    var turnToConfig = {
        siteKey: "<?= $siteKey ?>",
        orderConfFlowPauseSeconds:0,
        <?php if ($checkoutCommentsSuccessEnabled): ?>
            commentCaptureShowUsername: true,
            embedCommentCapture: <?= var_export($checkoutCommentsSuccessEnabled, true) ?>,
        <?php endif; ?>
        postPurchaseFlow:true
    };
</script>

<script src='<?= $staticUrl ?>/tra<?= $version ?>/turntoFeed.js' type='text/javascript'></script>

<script src='<?= $staticUrl ?>/traServer<?= $version ?>/trajs/<?= $siteKey ?>/tra.js' type='text/javascript'></script>

<script type="text/javascript">
    TurnToFeed.addFeedPurchaseOrder(<?= $block->getFeedPurchaseOrderData() ?>);

    <?php foreach($block->getOrderItemData() as $item): ?>
            TurnToFeed.addFeedLineItem(<?= $item ?>);
    <?php endforeach; ?>

    TurnToFeed.sendFeed();
</script>

<?php if ($checkoutCommentsSuccessEnabled): ?>
    <div id="TTcommentCapture"></div>
<?php endif; ?>
