<?php
/**
 * Copyright © Emplifi, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\View\Element\Template;
use TurnTo\SocialCommerce\ViewModel\JSOrderFeed;

/**
 * @var Template $block
 * @var JSOrderFeed $viewModel
 */
$viewModel = $block->getViewModel();
?>

<script type="text/javascript">
    TurnToCmd('feed.send', <?= $viewModel->getFeedPurchaseOrderData() ?>);
</script>
