<?php
/**
 * Copyright © Emplifi, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\View\Element\Template;
use TurnTo\SocialCommerce\ViewModel\JSOrderFeed;

/**
 * @var Template $block
 * @var JSOrderFeed $viewModel
 */
$viewModel = $block->getViewModel();
?>

<script>
    let turnToOrderFeedData = <?= /* @noEscape */ $viewModel->getFeedPurchaseOrderData() ?>;
    if (!turnToOrderFeedData || turnToOrderFeedData.error) {
        console.error('TurnTo order feed payload invalid or unavailable.', turnToOrderFeedData);
    } else {
        TurnToCmd('feed.send', turnToOrderFeedData);
    }
</script>
