<?php
/**
 * TurnTo_SocialCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2018 TurnTo Networks, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var \TurnTo\SocialCommerce\Block\Widget\Pinboard $block */
/** @var TurnTo\SocialCommerce\Helper\Config $configHelper */
$configHelper = $this->helper(\TurnTo\SocialCommerce\Helper\Config::class);

$staticUrl = preg_replace("(^https?://)", "//", $configHelper->getStaticUrl());

echo $block->getTurnToConfigHtml();

?>

<div id="tt-gallery-row"></div>
