<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $helper = $this->helper('TurnTo\SocialCommerce\Helper\Config'); ?>
<?php $turnToIsEnabled = $helper->getIsEnabled($helper->getCurrentStoreCode());?>
<?php $count = $block->getReviewsCount($turnToIsEnabled); ?>
<?php $url = $block->getReviewsUrl() . '#reviews'; ?>
<?php $urlForm = $block->getReviewsUrl() . '#review-form'; ?>
<?php if ($count): ?>
    <?php $rating = $block->getRatingSummary($turnToIsEnabled); ?>
    <div class="product-reviews-summary short<?php echo !$rating ? ' no-rating' : ''?>">
        <?php if ($rating):?>
            <div class="rating-summary">
                <span class="label"><span><?php /* @escapeNotVerified */ echo __('Rating') ?>:</span></span>
                <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $rating; ?>%">
                    <span style="width:<?php /* @escapeNotVerified */ echo $rating; ?>%"><span><?php /* @escapeNotVerified */ echo $rating; ?>%</span></span>
                </div>
            </div>
        <?php endif;?>
        <div class="reviews-actions">
            <a class="action view" href="<?php /* @escapeNotVerified */ echo $url ?>"><?php /* @escapeNotVerified */ echo $count ?>&nbsp;<span><?php /* @escapeNotVerified */ echo($count == 1) ? __('Review') : __('Reviews') ?></span></a>
        </div>
    </div>
<?php elseif ($block->getDisplayIfEmpty()): ?>
    <div class="product-reviews-summary short empty">
        <div class="reviews-actions">
            <a class="action add" href="<?php /* @escapeNotVerified */ echo $urlForm; ?>">
                <?php /* @escapeNotVerified */ echo __('Be the first to review this product') ?>
            </a>
        </div>
    </div>
<?php endif; ?>
