<?php
/**
 * Copyright © Emplifi, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Backend\Block\Template;
use TurnTo\SocialCommerce\ViewModel\Widget as ViewModel;

/**
 * @var Template $block
 * @var ViewModel $viewModel
 */
$viewModel = $block->getViewModel();
?>
<?php if (empty($viewModel->getSiteKey()) || empty($viewModel->getAuthorizationKey())): ?>
    <div class="messages">
        <div class="message message-warning warning">
            <div data-ui-id="messages-message-warning">
                <p>This feature requires that you enter your Emplifi Ratings & Reviews Site Key and Authorization Key in
                    the <a href="<?= $viewModel->storeConfigUrl() ?>">system configuration</a>.
                </p>
                <p>You can find your Site Key and Auth Key in the
                    <a href="https://emplifi.io/login" class="external-link" target="_blank"
                       rel="nofollow noopener" title="Follow link">Emplifi portal</a>
                    or by contacting your Customer Success team.
                </p>
            </div>
        </div>
    </div>
<?php endif; ?>

