<?php
/**
 * Copyright © Emplifi, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Backend\Block\Template;
use TurnTo\SocialCommerce\ViewModel\Widget as ViewModel;

/**
 * @var Template $block
 * @var ViewModel $viewModel
 */
$viewModel = $block->getViewModel();
?>
<?php if (empty($viewModel->getSiteKey()) || empty($viewModel->getAuthorizationKey())): ?>
    <div class="messages">
        <div class="message message-warning warning">
            <div data-ui-id="messages-message-warning">
                <p>
                    <?= $block->escapeHtml(
                        __(
                            'This feature requires that you enter your '
                            . 'Emplifi Ratings & Reviews Site Key and Authorization Key in the'
                        )
                    ) ?>
                    <a href="<?= $block->escapeUrl($viewModel->storeConfigUrl()) ?>">
                        <?= $block->escapeHtml(__('system configuration')) ?>
                    </a>.
                </p>
                <p>
                    <?= $block->escapeHtml(__('You can find your Site Key and Auth Key in the')) ?>
                    <a href="<?= $block->escapeUrl('https://emplifi.io/login') ?>"
                       class="external-link"
                       target="_blank"
                       rel="nofollow noopener"
                       title="<?= $block->escapeHtmlAttr(__('Follow link')) ?>">
                        <?= $block->escapeHtml(__('Emplifi portal')) ?>
                    </a>
                    <?= $block->escapeHtml(__('or by contacting your Customer Success team.')) ?>
                </p>
            </div>
        </div>
    </div>
<?php endif; ?>
