<?php
/**
* TurnTo_SocialCommerce
*
* NOTICE OF LICENSE
*
* This source file is subject to the Open Software License (OSL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/osl-3.0.php
*
* @copyright  Copyright (c) 2018 TurnTo Networks, Inc.
* @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
*/

/** @var TurnTo\SocialCommerce\Helper\Config $configHelper */
$configHelper = $this->helper('TurnTo\SocialCommerce\Helper\Config');

$qaEnabled = $configHelper->getQaEnabled();
$qaTeaserEnabled = $configHelper->getQaTeaserEnabled();
$reviewsEnabled = $configHelper->getReviewsEnabled();
$reviewsTeaserEnabled = $configHelper->getReviewsTeaserEnabled();

if ($qaEnabled && $qaTeaserEnabled): ?>
    <script type="text/javascript">
        function qaTeaser() {
            if (typeof(TurnToItemData) == 'undefined' || typeof(TurnToItemData.counts) == 'undefined') {
                return '';
            } else {
                var answerCount = TurnToItemData.counts.a;
                var questionCount = TurnToItemData.counts.q;
                var teaserContainer = TurnTojQuery(".TurnToItemTeaser");
                var teaserHtml = '';
                <?php
                if ($reviewsEnabled && $reviewsTeaserEnabled):
                ?>
                var teaserHtml = '&nbsp;|&nbsp;';
                <?php
                endif;
                ?>

                if (questionCount == 0) {
                    teaserHtml = teaserHtml + '<a id="askQuestion" href="javascript:void(0)"><?= __('Ask a Question') ?></a>';
                } else {
                    teaserHtml = teaserHtml + '<a id="readQuestions" href="javascript:void(0)">' + questionCount + ' Question' + (questionCount == 1 ? '' : 's') + ', ' + answerCount + ' Answer' + (answerCount == 1 ? '' : 's') + '</a>';
                }

                var reviewCount = TurnToItemData.counts.r;

                // Fill container with Q&A content
                teaserContainer.html(teaserHtml);

                // Add the appropriate listeners to the links
                scrollToTab(teaserContainer, '#askQuestion', '#turnto_qa', '#tab-label-turnto_qa-title');

                scrollToTab(teaserContainer, '#readQuestions', '#turnto_qa', '#tab-label-turnto_qa-title');
            }
        }
    </script>
<?php endif;
