<?php
/**
 * TurnTo_SocialCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2018 TurnTo Networks, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var TurnTo\SocialCommerce\Helper\Config $configHelper */
$configHelper = $this->helper('TurnTo\SocialCommerce\Helper\Config');

$reviewsEnabled = $configHelper->getReviewsEnabled();
$reviewsTeaserEnabled = $configHelper->getReviewsTeaserEnabled();

if ($reviewsEnabled && $reviewsTeaserEnabled): ?>
    <script type="text/javascript">
        function reviewsTeaser() {
            if (typeof(TurnToItemData) == 'undefined' || typeof(TurnToItemData.counts) == 'undefined') {
                return '';
            } else {
                var reviewCount = TurnToItemData.counts.r;
                var teaserContainer = TurnTojQuery(".TurnToReviewsTeaser");
                var teaserHtml = '';

                // round the average rating to the nearest tenth
                var rating = Math.round((TurnToItemData.counts.ar + 0.25) * 100.0) / 100.0;
                rating = rating.toString();
                var decimal = parseInt(rating.substring(2, 3));
                rating = rating.substring(0, 1) + "-" + (decimal >= 5 ? '5' : '0');

                if (reviewCount == 0) {
                    teaserHtml = '<div class="TT2left TTratingBox TTrating-0-0"></div> <a id="writeReview" href="javascript:void(0)"><?= __('Write a Review') ?></a>';
                } else {
                    teaserHtml = '<div class="TTratingBox TTrating-' + rating + '"></div><a id="readReviews" href="javascript:void(0)">' + reviewCount + ' Review' + (reviewCount == 1 ? '' : 's') + '</a>';
                }

                teaserContainer.html(teaserHtml);

                scrollToTab(teaserContainer, '#readReviews', '#turnto_reviews', '#tab-label-turnto_reviews-title');

                // Listener on 'write review' link
                teaserContainer.find('#writeReview').click(function (e) {
                    TurnTo.writeReview();
                });
            }
        }
    </script>
<?php endif;
