<?php
/**
 * TurnTo_SocialCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2017 TurnTo Networks, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var TurnTo\SocialCommerce\Helper\Config $configHelper */
$configHelper = $this->helper('TurnTo\SocialCommerce\Helper\Config');

$singleSignOn = $configHelper->getSingleSignOn();

if ($singleSignOn): ?>
    <script type="text/javascript">
        function localLogoutFunction(callbackFn) {
            require(['jquery', 'mage/url'], function ($, urlBuilder) {
                urlBuilder.setBaseUrl('<?= $block->getBaseUrl() ?>');
                $.ajax({
                    type: "POST",
                    url: urlBuilder.build('customer/account/logout')
                }).done(function(result) {
                    callbackFn(JSON.parse(result.responseText));
                });
            });
        }

        function localGetLoginStatusFunction(callbackFn) {
            localGetUserInfoFunction(callbackFn);
        }

        function localGetUserInfoFunction(callbackFn) {
            require(['jquery', 'mage/url'], function ($, urlBuilder) {
                urlBuilder.setBaseUrl('<?= $block->getBaseUrl() ?>');
                $.ajax({
                    type: "POST",
                    url: urlBuilder.build('turnto/sso/getUserStatus')
                }).done(function (userInfo) {
                    if (userInfo.error || userInfo.payload.user_auth_token == null) {
                        callbackFn({user_auth_token: null});
                    }
                    else {
                        callbackFn(userInfo.payload, userInfo.signature);
                    }
                });
            });
        }
    </script>
<?php endif;
